### ISSUE TITLE
C182 project question

### ISSUE THREAD

**Issue by BPieke** [AlexChesters/c182rg-improvement-project#35]
Hi, I am impressed that you have managed to fix the autopilot power issue!  In the past, I fixed many Carenado autopilots in FSX and P3D, but am totally stumped by the encryption in MSFS.. How do you get around that?

**Comment by BPieke** [comment]
Edit.. figured it out and modified the code:
 var avionics = SimVar.GetSimVarValue("ELECTRICAL MASTER BATTERY", "bool");

Now it works for me..

**Comment by AlexChesters** [comment]
Thanks for reaching out! 😄 

> I fixed many Carenado autopilots in FSX and P3D, but am totally stumped by the encryption in MSFS.. How do you get around that?

I don't do anything with the encrypted elements of the 182 RG II in any way, the autopilot code isn't encrypted 😄 

The nature of MSFS mods is such that anything you provide in your community folder can overwrite the stuff in the official folder (e.g. default planes and marketplace planes); this mod works by providing a custom [`panel.cfg`](https://github.com/AlexChesters/c182rg-improvement-project/blob/main/c182rg-improvement-project/SimObjects/Airplanes/Carenado_C182RG/panel/PANEL.CFG) which ensures the 182 RG II points at my custom autopilot code rather than the one provided by the plane itself

Does this answer your question? 😄

**Comment by AlexChesters** [comment]
I'm interested in learning more about the code change you needed to make though, I haven't run into the issue you're describing with the latest version of this mod

Can you tell me a bit more about the situations where the autopilot panel is still illuminated despite power being available to the aircraft? Does this occur when you spawn at a parking stand?

**Comment by BPieke** [comment]
Yes, either spawning cold&dark or turning off the battery switch.
![182rg](https://github.com/AlexChesters/c182rg-improvement-project/assets/71661698/cbbf1154-4ff9-4b92-aecf-a75dc32b32a2)

**Comment by AlexChesters** [comment]
covered this issue via email, bug is fixed in 8c8cb37c6c74d9eda430e241bef11e35110e44c9

**Comment by BPieke** [comment]
Thanks Alex!
